package alxnns1.mobhunter.init;

import alxnns1.mobhunter.crafting.ArmourCraftingRecipe;
import alxnns1.mobhunter.crafting.WeaponCraftingRecipe;
import alxnns1.mobhunter.reference.MetaRef;
import alxnns1.mobhunter.reference.Names;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.registries.IForgeRegistry;

/**
 * Contains the recipes to be added
 * Created by Mark on 21/04/2016.
 */
public class MHRecipes
{
	//Leaving these old recipes commented out here so we can add them as json recipes later

	//TODO Add Dash Extract
	//GameRegistry.addShapelessRecipe(
	//      MetaRef.getStack(MetaRef.EnumItemType.DRINK, Names.Items.MEGA_DASH_JUICE),
	//      Items.GLASS_BOTTLE,
	//      MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.DASH_EXTRACT),
	//      MHItems.itemDoneSteak);
	//TODO Add Pale Extract
	//GameRegistry.addShapelessRecipe(
	//      MetaRef.getStack(MetaRef.EnumItemType.DRINK, Names.Items.MEGA_DEMONDRUG),
	//      MetaRef.getStack(MetaRef.EnumItemType.DRINK, Names.Items.DEMONDRUG),
	//      MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PALE_EXTRACT);
	//TODO Add Pale Extract
	//GameRegistry.addShapelessRecipe(
	//      MetaRef.getStack(MetaRef.EnumItemType.DRINK, Names.Items.MEGA_ARMOURSKIN),
	//      MetaRef.getStack(MetaRef.EnumItemType.DRINK, Names.Items.ARMOURSKIN),
	//      MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PALE_EXTRACT);

	public static void regSmelting()
	{
		GameRegistry.addSmelting(MHItems.itemRawMeat,
				new ItemStack(MHItems.itemRareSteak), 0.2f);
		GameRegistry.addSmelting(MHBlocks.blockOreMachalite,
				MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT), 0.2f);
		GameRegistry.addSmelting(MHBlocks.blockOreDragonite,
				MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.DRAGONITE_INGOT), 0.2f);
		GameRegistry.addSmelting(MHBlocks.blockOreGossamite,
				MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.GOSSAMITE_INGOT), 0.2f);
	}

	public static void regWeaponRecipes(IForgeRegistry<WeaponCraftingRecipe> registry)
	{
		registry.registerAll(
				new WeaponCraftingRecipe(MHItems.weaponHuntersKnife, new ItemStack(Items.IRON_INGOT, 6)),
				new WeaponCraftingRecipe(MHItems.weaponSoldiersDagger, MHItems.weaponHuntersKnifePlus,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 5)),
				new WeaponCraftingRecipe(MHItems.weaponCommandersDagger, MHItems.weaponSoldiersDagger,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 5)),
				new WeaponCraftingRecipe(MHItems.weaponDeadlyKnife, MHItems.weaponCommandersDagger,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW, 6),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.DRAGONITE_INGOT, 3)),
				new WeaponCraftingRecipe(MHItems.weaponDeadlyKnifePlus, MHItems.weaponDeadlyKnife,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.KINGS_FRILL, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_PLUS, 2),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.DRAGONITE_INGOT, 7)),
//                new WeaponCraftingRecipe(MHItems.weaponNatchKnife, MHItems.weaponDeadlyKnifePlus,
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW_PLUS, 4),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE_PLUS, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.KINGS_FRILL, 2),
//                        MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.CARBALITE_INGOT, 5)),
//                new WeaponCraftingRecipe(MHItems.weaponAcclimatedKnife, MHItems.weaponNatchKnife,
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW_PLUS, 3),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.AVIAN_FINEBONE, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE_PLUS, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_GEM, 1)),
//                new WeaponCraftingRecipe(MHItems.weaponRebelliousKnife, MHItems.weaponAcclimatedKnife,
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW_PLUS, 4),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.TOUGH_BIRD_WYVERN_HIDE, 2),
//                        MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.FUCIUM_INGOT, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_GEM, 2)),
//                new WeaponCraftingRecipe(MHItems.weaponRebelliousKnifePlus, MHItems.weaponRebelliousKnife,
//                        MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.ELTALITE_INGOT, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.AVIAN_STOUTBONE, 5),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW_PLUS, 5));
//                new WeaponCraftingRecipe(MHItems.weaponVengefulKnife, MHItems.weaponRebelliousKnifePlus,
//                        MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MELDSPAR_INGOT, 3),
//                        MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.ELTALITE_INGOT, 10),
//                        MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_GEM, 3)),
				new WeaponCraftingRecipe(MHItems.weaponSerpentBite, MHItems.weaponHuntersKnife,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE, 5),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_FANG, 10),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 3)),
//				new WeaponCraftingRecipe(MHItems.weaponSerpentBitePlus, MHItems.weaponSerpentBite,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE_PLUS, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_FANG, 15),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 5)),
//				new WeaponCraftingRecipe(MHItems.weaponDeadlock, MHItems.weaponSerpentBitePlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE_PLUS, 9),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_FANG, 20),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_L, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.AVIAN_STOUTBONE, 5)),
				new WeaponCraftingRecipe(MHItems.weaponVelocidromeBite, MHItems.weaponSerpentBite,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HEAD),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 4)),
				new WeaponCraftingRecipe(MHItems.weaponVelocidromeBitePlus, MHItems.weaponVelocidromeBite,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW, 6),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HEAD, 1),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.JUMBO_BONE, 3)),
//				new WeaponCraftingRecipe(MHItems.weaponVelocidromeFang, MHItems.weaponVelocidromeBitePlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_PLUS, 1),
//						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 5)),
//				new WeaponCraftingRecipe(MHItems.weaponVelocidromeFangPlus, MHItems.weaponVelocidromeFang,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE_PLUS, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.TOUGH_BIRD_WYVERN_HIDE, 4)),
//				new WeaponCraftingRecipe(MHItems.weaponDromeRushDagger, MHItems.weaponVelocidromeFangPlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_SCALE_PLUS, 4),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_GEM, 1)),
//				new WeaponCraftingRecipe(MHItems.weaponGreatStabberdag, MHItems.weaponDromeRushDagger,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HARDCLAW, 4),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.TOUGH_BIRD_WYVERN_HIDE, 8),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.FEY_WYVERN_GEM, 2)),
				new WeaponCraftingRecipe(MHItems.weaponSnakeBite, MHItems.weaponHuntersKnife,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_HIDE, 5),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_FANG, 10),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.FROST_SAC, 1)),
//				new WeaponCraftingRecipe(MHItems.weaponSnakeBitePlus, MHItems.weaponSnakeBite,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_HIDE_PLUS, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_FANG, 15),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 5),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.FROST_SAC, 2)),
//				new WeaponCraftingRecipe(MHItems.weaponDeathlyCold, MHItems.weaponSnakeBitePlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_HIDE_PLUS, 9),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GIAPREY_FANG, 20),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.AVIAN_STOUTBONE, 5),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.FROST_SAC, 3)),
				new WeaponCraftingRecipe(MHItems.weaponViperBite, MHItems.weaponHuntersKnife,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE, 5),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_FANG, 10),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 1)),
//				new WeaponCraftingRecipe(MHItems.weaponViperBitePlus, MHItems.weaponViperBite,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE_PLUS, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_FANG, 15),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 5),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 2)),
//				new WeaponCraftingRecipe(MHItems.weaponDeathprize, MHItems.weaponViperBitePlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE_PLUS, 9),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_FANG, 20),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_L, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 3)),
				new WeaponCraftingRecipe(MHItems.weaponGendromeBite, MHItems.weaponViperBite,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HEAD),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 4),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 1)),
				new WeaponCraftingRecipe(MHItems.weaponGendromeBitePlus, MHItems.weaponGendromeBite,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HIDE, 6),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HEAD, 1),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.JUMBO_BONE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 2)),
//				new WeaponCraftingRecipe(MHItems.weaponGendromeFang, MHItems.weaponGendromeBitePlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_PLUS, 1),
//						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 5),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 3)),
//				new WeaponCraftingRecipe(MHItems.weaponGendromeFangPlus, MHItems.weaponGendromeFang,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE_PLUS, 7),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.TOUGH_BIRD_WYVERN_HIDE, 4),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 4)),
//				new WeaponCraftingRecipe(MHItems.weaponDromeToxinDagger, MHItems.weaponGendromeFangPlus,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_SCALE_PLUS, 4),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW_PLUS, 3),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_GEM, 1),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 5)),
//				new WeaponCraftingRecipe(MHItems.weaponGreatParadag, MHItems.weaponDromeToxinDagger,
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HARDCLAW, 4),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.TOUGH_BIRD_WYVERN_HIDE, 8),
//						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.FEY_WYVERN_GEM, 2),
//						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 6)),
				new WeaponCraftingRecipe(MHItems.weaponHydraBite, MHItems.weaponHuntersKnife,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.IOPREY_HIDE, 5),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.IOPREY_FANG, 4),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 3)),
				new WeaponCraftingRecipe(MHItems.weaponHydraBitePlus, MHItems.weaponHydraBite,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.IOPREY_FANG, 6),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 6),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.POISON_SAC, 2)),
				new WeaponCraftingRecipe(MHItems.weaponDeadlyPoison, MHItems.weaponHydraBitePlus,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.IOPREY_FANG, 9),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M, 9),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.POISON_SAC, 4)),
				new WeaponCraftingRecipe(MHItems.weaponHuntersKnifePlus, MHItems.weaponHuntersKnife,
						new ItemStack(Items.IRON_INGOT, 5)),
				new WeaponCraftingRecipe(MHItems.weaponHuntersDagger, MHItems.weaponHuntersKnifePlus,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 4),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER)),
				new WeaponCraftingRecipe(MHItems.weaponAssassinsDagger, MHItems.weaponHuntersDagger,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 4),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.DRAGONITE_INGOT, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER)),

				new WeaponCraftingRecipe(MHItems.weaponBoneKris,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MYSTERY_BONE),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2)),
				new WeaponCraftingRecipe(MHItems.weaponBoneKrisPlus, MHItems.weaponBoneKris,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.BIRD_WYVERN_FANG, 3)),
				new WeaponCraftingRecipe(MHItems.weaponChiefKris, MHItems.weaponBoneKrisPlus,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.BONE_HUSK, 5),
						new ItemStack(Items.IRON_INGOT, 3)),
				new WeaponCraftingRecipe(MHItems.weaponRottonSword, MHItems.weaponBoneKris,
						new ItemStack(Items.ROTTEN_FLESH, 7),
						new ItemStack(Items.SKULL, 1, 2)),
				new WeaponCraftingRecipe(MHItems.weaponPlaguedSword, MHItems.weaponRottonSword,
						new ItemStack(Items.ROTTEN_FLESH, 6),
						new ItemStack(Items.SKULL, 2, 2)),
				new WeaponCraftingRecipe(MHItems.weaponInfestedSword, MHItems.weaponPlaguedSword,
						new ItemStack(Items.ROTTEN_FLESH, 5),
						new ItemStack(Items.SKULL, 3, 2)),
				new WeaponCraftingRecipe(MHItems.weaponSkeletalSword, MHItems.weaponBoneKris,
						new ItemStack(Items.BONE, 7),
						new ItemStack(Items.SKULL, 1, 0)),
				new WeaponCraftingRecipe(MHItems.weaponSkeletalSwordPlus, MHItems.weaponSkeletalSword,
						new ItemStack(Items.BONE, 6),
						new ItemStack(Items.SKULL, 2, 0)),
				new WeaponCraftingRecipe(MHItems.weaponWitheredSword, MHItems.weaponSkeletalSwordPlus,
						new ItemStack(Items.BONE, 6),
						new ItemStack(Items.SKULL, 1, 1),
						Items.COAL),
				new WeaponCraftingRecipe(MHItems.weaponWitheredSwordPlus, MHItems.weaponWitheredSword,
						new ItemStack(Items.BONE, 3),
						new ItemStack(Items.SKULL, 2, 1),
						new ItemStack(Items.COAL, 3)),
				new WeaponCraftingRecipe(MHItems.weaponNecrosisBlade, MHItems.weaponWitheredSwordPlus,
						new ItemStack(Items.BONE, 3),
						new ItemStack(Items.SKULL, 1, 1),
						Items.NETHER_STAR,
						new ItemStack(Items.COAL, 3)),
				new WeaponCraftingRecipe(MHItems.weaponMandiblade, MHItems.weaponBoneKris,
						new ItemStack(Items.STRING, 7),
						Items.SPIDER_EYE),
				new WeaponCraftingRecipe(MHItems.weaponMandibladePlus, MHItems.weaponMandiblade,
						new ItemStack(Items.STRING, 6),
						new ItemStack(Items.SPIDER_EYE, 2)),
				new WeaponCraftingRecipe(MHItems.weaponStingingMandiblade, MHItems.weaponMandibladePlus,
						new ItemStack(Items.STRING, 6),
						Items.SPIDER_EYE,
						Items.FERMENTED_SPIDER_EYE),
				new WeaponCraftingRecipe(MHItems.weaponPoisonStingblade, MHItems.weaponStingingMandiblade,
						new ItemStack(Items.STRING, 3),
						new ItemStack(Items.SPIDER_EYE, 3),
						new ItemStack(Items.FERMENTED_SPIDER_EYE, 2)),
				new WeaponCraftingRecipe(MHItems.weaponFearSword, MHItems.weaponBoneKris,
						new ItemStack(Items.GUNPOWDER, 7),
						new ItemStack(Items.SKULL, 1, 4)),
				new WeaponCraftingRecipe(MHItems.weaponTerrorSword, MHItems.weaponFearSword,
						new ItemStack(Items.GUNPOWDER, 6),
						new ItemStack(Items.SKULL, 2, 4)),
				new WeaponCraftingRecipe(MHItems.weaponDreadSword, MHItems.weaponTerrorSword,
						new ItemStack(Items.GUNPOWDER, 3),
						new ItemStack(Items.SKULL, 3, 4),
						new ItemStack(Blocks.TNT, 2)),
				new WeaponCraftingRecipe(MHItems.weaponXenoblade, MHItems.weaponBoneKris,
						new ItemStack(Items.ENDER_PEARL, 5)),
				new WeaponCraftingRecipe(MHItems.weaponXenobladePlus, MHItems.weaponXenoblade,
						new ItemStack(Items.ENDER_PEARL, 7),
						Items.ENDER_EYE),
				new WeaponCraftingRecipe(MHItems.weaponAstralSword, MHItems.weaponXenobladePlus,
						new ItemStack(Items.ENDER_PEARL, 3),
						new ItemStack(Items.ENDER_EYE, 2),
						new ItemStack(Blocks.END_STONE, 3)),
				new WeaponCraftingRecipe(MHItems.weaponAstralEndsword, MHItems.weaponAstralSword,
						new ItemStack(Items.ENDER_EYE, 3),
						Blocks.DRAGON_EGG,
						Items.DRAGON_BREATH,
						new ItemStack(Blocks.END_STONE, 3)),
				new WeaponCraftingRecipe(MHItems.weaponSlimySword, MHItems.weaponBoneKris,
						new ItemStack(Items.SLIME_BALL, 5)),
				new WeaponCraftingRecipe(MHItems.weaponSlimySwordPlus, MHItems.weaponSlimySword,
						new ItemStack(Items.SLIME_BALL, 5),
						new ItemStack(Blocks.SLIME_BLOCK, 3)),
				new WeaponCraftingRecipe(MHItems.weaponCrystalizedSlimeblade, MHItems.weaponSlimySwordPlus,
						new ItemStack(Items.SLIME_BALL, 3),
						new ItemStack(Items.MAGMA_CREAM, 2),
						new ItemStack(Blocks.SLIME_BLOCK, 3)),
				new WeaponCraftingRecipe(MHItems.weaponMagmaticSlimeblade, MHItems.weaponCrystalizedSlimeblade,
						new ItemStack(Items.MAGMA_CREAM, 3),
						new ItemStack(Blocks.SLIME_BLOCK, 3),
						new ItemStack(Items.BLAZE_POWDER, 2)),
				new WeaponCraftingRecipe(MHItems.weaponBlazingSword, MHItems.weaponBoneKris,
						new ItemStack(Items.BLAZE_ROD, 2),
						new ItemStack(Items.BLAZE_POWDER, 3)),
				new WeaponCraftingRecipe(MHItems.weaponBlazingTempest, MHItems.weaponBlazingSword,
						new ItemStack(Items.BLAZE_ROD, 6),
						new ItemStack(Items.BLAZE_POWDER, 3)),
				new WeaponCraftingRecipe(MHItems.weaponBlazingInferno, MHItems.weaponBlazingTempest,
						new ItemStack(Items.BLAZE_ROD, 3),
						new ItemStack(Items.BLAZE_POWDER, 3),
						new ItemStack(Items.FIRE_CHARGE, 2))
		);
	}

	public static void regArmourRecipes(IForgeRegistry<ArmourCraftingRecipe> registry)
	{
		registry.registerAll(
				new ArmourCraftingRecipe(MHItems.armourDerringHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S)),
				new ArmourCraftingRecipe(MHItems.armourDerringChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						Items.IRON_INGOT),
				new ArmourCraftingRecipe(MHItems.armourDerringLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S),
						Items.IRON_INGOT),
				new ArmourCraftingRecipe(MHItems.armourDerringBoots,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S)),

				new ArmourCraftingRecipe(MHItems.armourHunterHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT),
						Items.IRON_INGOT,
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER, 2)),
				new ArmourCraftingRecipe(MHItems.armourHunterChestplate,
						new ItemStack(Items.IRON_INGOT, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL),
						MetaRef.getStack(MetaRef.EnumItemType.PLANT, Names.Items.IVY)),
				new ArmourCraftingRecipe(MHItems.armourHunterLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 2),
						Items.IRON_INGOT,
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER)),
				new ArmourCraftingRecipe(MHItems.armourHunterBoots,
						Items.IRON_INGOT,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2)),

				new ArmourCraftingRecipe(MHItems.armourBoneHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MYSTERY_BONE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.UNKNOWN_SKULL),
						MetaRef.getStack(MetaRef.EnumItemType.NEOPTERAN_DROP, Names.Items.ALTAROTH_JAW)),
				new ArmourCraftingRecipe(MHItems.armourBoneChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MYSTERY_BONE, 4),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.JUMBO_BONE),
						MetaRef.getStack(MetaRef.EnumItemType.NEOPTERAN_DROP, Names.Items.ALTAROTH_STOMACH, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_FLUID)),
				new ArmourCraftingRecipe(MHItems.armourBoneLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MYSTERY_BONE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BEAST_DROP, Names.Items.SHARP_FANG, 2)),
				new ArmourCraftingRecipe(MHItems.armourBoneBoots,
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MYSTERY_BONE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_M),
						MetaRef.getStack(MetaRef.EnumItemType.BEAST_DROP, Names.Items.SHARP_FANG)),

				new ArmourCraftingRecipe(MHItems.armourAlloyHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2),
						new ItemStack(Items.IRON_INGOT, 3)),
				new ArmourCraftingRecipe(MHItems.armourAlloyChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 5),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						new ItemStack(Items.IRON_INGOT, 6),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2)),
				new ArmourCraftingRecipe(MHItems.armourAlloyLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 2),
						new ItemStack(Items.IRON_INGOT, 3)),
				new ArmourCraftingRecipe(MHItems.armourAlloyBoots,
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 4),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2),
						new ItemStack(Items.IRON_INGOT, 2)),

				new ArmourCraftingRecipe(MHItems.armourJaggiHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE, 2),
						new ItemStack(Items.IRON_INGOT, 3)),
				new ArmourCraftingRecipe(MHItems.armourJaggiChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.KINGS_FRILL),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_CLAW, 4),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2),
						new ItemStack(Items.IRON_INGOT, 3)),
				new ArmourCraftingRecipe(MHItems.armourJaggiLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GREAT_JAGGI_HIDE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.KINGS_FRILL),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL)),
				new ArmourCraftingRecipe(MHItems.armourJaggiBoots,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_HIDE, 4),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.JAGGI_SCALE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 4),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.MACHALITE_INGOT, 2)),

				new ArmourCraftingRecipe(MHItems.armourVelocipreyHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_SCALE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER, 2)),
				new ArmourCraftingRecipe(MHItems.armourVelocipreyChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_CLAW, 4),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.SCREAMER_SAC, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_SCALE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER, 2),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 3)),
				new ArmourCraftingRecipe(MHItems.armourVelocipreyLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIDROME_HIDE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.SCREAMER_SAC, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2)),
				new ArmourCraftingRecipe(MHItems.armourVelocipreyBoots,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_HIDE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.VELOCIPREY_SCALE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 4),
						new ItemStack(Items.IRON_INGOT, 4)),

				new ArmourCraftingRecipe(MHItems.armourGenpreyHelmet,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_SCALE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER, 2)),
				new ArmourCraftingRecipe(MHItems.armourGenpreyChestplate,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_CLAW, 4),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_SCALE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BUG, Names.Items.GLUEGLOPPER, 2),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 3)),
				new ArmourCraftingRecipe(MHItems.armourGenpreyLeggings,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENDROME_HIDE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.PARALYSIS_SAC, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.ORE, Names.Items.EARTH_CRYSTAL, 2)),
				new ArmourCraftingRecipe(MHItems.armourGenpreyBoots,
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_HIDE, 2),
						MetaRef.getStack(MetaRef.EnumItemType.BIRD_DROP, Names.Items.GENPREY_SCALE, 3),
						MetaRef.getStack(MetaRef.EnumItemType.MISC_DROP, Names.Items.MONSTER_BONE_S, 4),
						new ItemStack(Items.IRON_INGOT, 4))
		);
	}
}
